# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
# The previous line enables IntelliSense for this file.
# See this post for more info https://www.meziantou.net/enabling-intellisense-for-github-actions-workflows-in-vs-code.htm

name: publish
on:
  pull_request:
    types: [closed]
    branches:
      - 'master'

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  NuGetDirectory: ${{ github.workspace }}/nuget

defaults:
  run:
    shell: pwsh

jobs:
  create_nuget:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0    
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    - name: Install GitVersion
      run: dotnet tool install --global GitVersion.Tool
    - name: Determine version
      id: gitversion
      run: dotnet-gitversion /output json /output buildserver
    - name: Build project
      run: dotnet build --configuration Release
    - name: Pack project
      run: dotnet pack --configuration Release --output ${{ env.NuGetDirectory }} /p:PackageVersion=${{ steps.gitversion.outputs['GitVersion.MajorMinorPatch'] }}
    - uses: actions/upload-artifact@v4
      with:
        name: nuget
        if-no-files-found: error
        retention-days: 7
        path: ${{ env.NuGetDirectory }}/*.nupkg

  validate_nuget:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    needs: [ create_nuget ]
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - uses: actions/download-artifact@v4
        with:
          name: nuget
          path: ${{ env.NuGetDirectory }}

      - name: Install nuget validator
        run: dotnet tool update Meziantou.Framework.NuGetPackageValidation.Tool --global

      # Validate the NuGet package: https://www.nuget.org/packages/Meziantou.Framework.NuGetPackageValidation.Tool#readme-body-tab
      # If some rules are not applicable, you can disable them using the --excluded-rules or --excluded-rule-ids option
      - name: Validate package
        run: meziantou.validate-nuget-package (Get-ChildItem "${{ env.NuGetDirectory }}/*.nupkg")

  run_test:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      ApiSettings__ValidBearerToken: ${{ secrets.INTEGRATION_API_TOKEN }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    - name: Run tests
      run: dotnet test --configuration Release -e ApiSettings__ValidBearerToken="${{ secrets.INTEGRATION_API_TOKEN }}"

  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    needs: [ validate_nuget, run_test ]
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/download-artifact@v4
      with:
        name: nuget
        path: ${{ env.NuGetDirectory }}
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.gitversion.outputs['GitVersion.MajorMinorPatch'] }}
        release_name: Release ${{ steps.gitversion.outputs['GitVersion.MajorMinorPatch'] }}
        draft: false
        prerelease: false
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ env.NuGetDirectory }}/*.nupkg
        asset_name: magecorp.clashroyaleapi.client.${{ steps.gitversion.outputs['GitVersion.MajorMinorPatch'] }}.nupkg
        asset_content_type: application/zip
    - name: Publish NuGet package
      run: |
        foreach($file in (Get-ChildItem "${{ env.NuGetDirectory }}" -Recurse -Include *.nupkg)) {
            dotnet nuget push $file --api-key "${{ secrets.NUGET_APIKEY }}" --source https://api.nuget.org/v3/index.json
        }
